/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Activity */
    get: operations["get_activity_api_activity_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Events */
    get: operations["events_api_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/worker/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause Worker
     * @description Pause every stage. A job already running finishes.
     */
    post: operations["pause_worker_api_worker_pause_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/worker/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resume Worker
     * @description Undo a global pause. Stages paused on their own stay paused.
     */
    post: operations["resume_worker_api_worker_resume_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/worker/stages/{stage}/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause Stage
     * @description Pause one stage. A job of that stage already running finishes.
     */
    post: operations["pause_stage_api_worker_stages__stage__pause_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/worker/stages/{stage}/resume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resume Stage */
    post: operations["resume_stage_api_worker_stages__stage__resume_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Activity */
    Activity: {
      /** Stages */
      stages: components["schemas"]["StageActivity"][];
      worker: components["schemas"]["WorkerActivity"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
    };
    /**
     * Stage
     * @enum {string}
     */
    Stage:
      | "metadata_write"
      | "scan"
      | "thumbnail"
      | "clip"
      | "quality"
      | "faces"
      | "recognize"
      | "layout"
      | "duplicates"
      | "atlases"
      | "llm_tag"
      | "noop";
    /** StageActivity */
    StageActivity: {
      /** Done */
      done: number;
      /** Errored */
      errored: number;
      /**
       * Kind
       * @enum {string}
       */
      kind: "item" | "batch";
      /** Parked */
      parked: number;
      /** Paused */
      paused: boolean;
      /** Pending */
      pending: number;
      /** Running */
      running: number;
      stage: components["schemas"]["Stage"];
      /** Total */
      total: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkerActivity */
    WorkerActivity: {
      /** Last Seen At */
      last_seen_at: string | null;
      /** Paused */
      paused: boolean;
      /** Quiet Until At */
      quiet_until_at: string | null;
      status: components["schemas"]["WorkerStatus"];
    };
    /**
     * WorkerStatus
     * @enum {string}
     */
    WorkerStatus: "running" | "paused" | "quiet" | "stopped";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_activity_api_activity_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Activity"];
        };
      };
    };
  };
  events_api_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  pause_worker_api_worker_pause_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Activity"];
        };
      };
    };
  };
  resume_worker_api_worker_resume_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Activity"];
        };
      };
    };
  };
  pause_stage_api_worker_stages__stage__pause_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stage: components["schemas"]["Stage"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Activity"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  resume_stage_api_worker_stages__stage__resume_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        stage: components["schemas"]["Stage"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Activity"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
