"""Phase 1 tables: items, jobs, job_stats

Revision ID: 0001
Revises:
Create Date: 2026-10-03 08:36:43.977893
"""

# Generated by Alembic and checked by hand: basic, not strict, type checking.
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "photo",
                "video",
                name="media_type",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_mtime_ns", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Double(), nullable=True),
        sa.Column("taken_at_local", sa.DateTime(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("missing_since", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "trashed",
                "purged",
                "missing",
                name="item_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.CheckConstraint("media_type IN ('photo', 'video')", name=op.f("ck_items_media_type")),
        sa.CheckConstraint(
            "status IN ('active', 'trashed', 'purged', 'missing')",
            name=op.f("ck_items_item_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_items_content_hash")),
    )
    op.create_table(
        "job_stats",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("processed", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("busy_seconds", sa.Double(), nullable=False),
        sa.PrimaryKeyConstraint("date", "stage", name=op.f("pk_job_stats")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "error",
                "parked",
                name="job_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("enqueued_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'done', 'error', 'parked')",
            name=op.f("ck_jobs_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_jobs_item_id_items"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            "ix_jobs_pending_by_priority",
            ["priority", "enqueued_at", "id"],
            unique=False,
            sqlite_where=sa.text("status = 'pending'"),
        )


def downgrade() -> None:
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_jobs_pending_by_priority", sqlite_where=sa.text("status = 'pending'")
        )
        batch_op.drop_index(batch_op.f("ix_jobs_item_id"))

    op.drop_table("jobs")
    op.drop_table("job_stats")
    op.drop_table("items")
