"""Job queue: retry_at for backoff, and indexes over open jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 13:10:11.284392
"""

# Generated by Alembic and checked by hand: basic, not strict, type checking.
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Open jobs: never tried, or failed and waiting to retry. Repeated literally, so
# this migration doesn't depend on app code.
OPEN = sa.text("status IN ('pending', 'error')")
WAS_PENDING = sa.text("status = 'pending'")


def upgrade() -> None:
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("retry_at", sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_jobs_pending_by_priority"), sqlite_where=WAS_PENDING)
        batch_op.create_index(
            "ix_jobs_open_by_priority",
            ["priority", "enqueued_at", "id"],
            unique=False,
            sqlite_where=OPEN,
        )
        batch_op.create_index(
            "uq_jobs_open_stage_item",
            ["stage", "item_id"],
            unique=True,
            sqlite_where=OPEN,
        )


def downgrade() -> None:
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("uq_jobs_open_stage_item", sqlite_where=OPEN)
        batch_op.drop_index("ix_jobs_open_by_priority", sqlite_where=OPEN)
        batch_op.create_index(
            batch_op.f("ix_jobs_pending_by_priority"),
            ["priority", "enqueued_at", "id"],
            unique=False,
            sqlite_where=WAS_PENDING,
        )
        batch_op.drop_column("retry_at")
