"""worker_controls: pause and resume, globally or per stage

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 20:34:33.439636
"""

# Generated by Alembic and checked by hand: basic, not strict, type checking.
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "worker_controls",
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("scope", name=op.f("pk_worker_controls")),
    )


def downgrade() -> None:
    op.drop_table("worker_controls")
