"""worker_heartbeat: whether the worker process is running

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 12:00:00.000000
"""

# Generated by Alembic and checked by hand: basic, not strict, type checking.
# pyright: basic

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "worker_heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("seen_at", sa.DateTime(), nullable=False),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_heartbeat")),
    )


def downgrade() -> None:
    op.drop_table("worker_heartbeat")
